# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

$script = <<-SCRIPT
sudo apt update
sudo apt -y upgrade
sudo apt install docker.io -y
sudo systemctl enable docker
curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add
sudo apt-add-repository "deb http://apt.kubernetes.io/ kubernetes-xenial main" -y
sudo apt install kubeadm -y
sudo swapoff -a
SCRIPT

Vagrant.configure(2) do |config|
  config.vm.define "masterk8s" do |masterk8s|

 	masterk8s.vm.box = "ubuntu/bionic64"
 	masterk8s.vm.network "forwarded_port", guest: 9000, host: 9001
  	#masterk8s.vm.network "public_network", bridge: "ens3"
  	masterk8s.vm.network "private_network", ip: "192.168.50.2"
	masterk8s.vm.hostname = "master"
	masterk8s.vm.provision "shell", inline: $script
  	masterk8s.vm.provider "virtualbox" do |vb|
      		vb.memory = "4096"
    	  	vb.name = "masterk8s"
  	end
end

config.vm.define "worker01" do |worker01|

 	worker01.vm.box = "ubuntu/bionic64"
  	#worker01.vm.network "public_network"
  	worker01.vm.network "private_network", ip: "192.168.50.3"
	worker01.vm.hostname = "worker01"
	worker01.vm.provision "shell", inline: $script
  	worker01.vm.provider "virtualbox" do |vb|
      		vb.memory = "1500"
    	  	vb.name = "worker01"
  	end
end
# config.vm.define "worker02" do |worker02|

#  	worker02.vm.box = "ubuntu/bionic64"
#   	worker02.vm.network "private_network", ip: "192.168.50.4"
# 	worker02.vm.hostname = "worker02"
# 	worker02.vm.provision "shell", inline: $script
#   	worker02.vm.provider "virtualbox" do |vb|
#       		vb.memory = "1500"
#     	  	vb.name = "worker02"
#   	end
# end
end
